# Generated by Django 2.2.1 on 2019-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.URLField()),
                ('url_image', models.URLField()),
                ('published_time', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=100000)),
            ],
        ),
    ]
