# Generated by Django 2.2.1 on 2019-09-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsAndUpdates',
            new_name='NewsAndUpdate',
        ),
    ]
